# -*- coding: utf-8 -*-
"""Aula 3 - Análise univariada de dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14d4sqbIFAAVKeI0dIVTEDO7bjItQ-Rxz
"""

Histograma

import matplotlib.pyplot as plt # Importa o matplotlib
import pandas as pd             # Importa o pandas

df = pd.read_csv('alunos.csv')  # Carrega o conjunto de dados

peso = df["Peso"]               # Isolaa variável "peso"

plt.figure(figsize=(8, 6))      # Define o tamenho da Fgura
plt.hist(peso, bins=range(40, 110, 10))
plt.title('Distribuição de Pesos')
plt.xlabel('Peso')
plt.ylabel('Alunos')
plt.show()

"""Gráfico de barras"""

import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('alunos.csv')

idade = df['Idade']
idade_sum = idade.value_counts()
idade_sum = idade_sum.sort_index()

x = idade_sum.index
y = idade_sum

plt.figure(figsize=(8, 6))
plt.bar(x, y)

plt.title('Distribuição de Idades')
plt.xlabel('Idade')
plt.ylabel('Alunos')
plt.xticks(x)
plt.show()

"""Box-plot"""

import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('alunos.csv')

alturas = df['Alt']                 # Seleciona a variável altura
alt_descri = alturas.describe()

q1 = alt_descri['25%']
mediana = alt_descri['50%']
q3 = alt_descri['75%']

s_q1 = '{0:.2f}'.format(q1)
s_mediana = '{0:.2f}'.format(mediana)
s_q3 = '{0:.2f}'.format(q3)

font_1 = {'family': 'serif', 'color': 'darkred', 'size': 14}

plt.figure(figsize=(6, 7))
plt.boxplot(alturas)
plt.title('Boxplot Alturas')
plt.ylabel('Altura')

plt.text(1, q1, s_q1, fontdict=font_1)
plt.text(1, mediana, s_mediana, fontdict=font_1)
plt.text(1, q3, s_q3, fontdict=font_1)

plt.show()

Violin Plot

import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('alunos.csv')

alturas = df['Alt']

plt.figure(figsize=(6, 7))
plt.violinplot(alturas)

plt.title('Violin-plot Alturas')
plt.ylabel('Altura')
plt.show()

"""Variável categórica nominal

"""

import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("alunos.csv")

df["Fuma"].value_counts(sort=False).plot.pie()
plt.show()

"""Variável Categórica Ordinal

"""

import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('alunos.csv')
toler = df['Toler']
toler_sum = toler.value_counts()
x = toler_sum.index
y = toler_sum

plt.figure(figsize=(8, 6))
plt.bar(x, y)
plt.title('Distribuição das Tolerâncias ao Fumo')
plt.ylabel('Quantidades')
plt.show()

"""Variável Numérica Discreta"""

import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('alunos.csv')
filhos = df['Filhos']
filhos_sum = filhos.value_counts()

x = filhos_sum.index
y = filhos_sum

plt.figure(figsize=(8, 6))
plt.vlines(x, 0, y)
plt.title('Número de Filhos')
plt.xlabel('Número de Filhos')
plt.ylabel('Frequência Absoluta')
plt.show()

"""Variável Numérica Contínua
Essa abaixo é bivariada
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

df = pd.read_csv('alunos.csv')
Peso = df['Peso']
Alt = df['Alt']
cores = (0, 0, 0)

plt.scatter(Peso, Alt, 20, c=cores, alpha=0.5)
plt.title('Alturas e Pesos dos alunos')
plt.xlabel('Pesos')
plt.ylabel('Alturas')
plt.show()