# -*- coding: utf-8 -*-
"""importando conjunto casas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qHtL7d6_u94tDaasuwtt3NzoJtUVMLLK
"""



import pandas as pd

df = pd.read_csv("exemplo_casas.csv")

# Primeiros registros
print("amostras:", df.head())